// vue/src/components/Avatar.vue
<script setup lang="ts">
import { Avatar } from "@ark-ui/vue";

type Props = {
  src: string;
  alt: string;
};

const props = defineProps<Props>();
</script>

<template>
  <Avatar.Root class="Avatar">
    <Avatar.Fallback class="Avatar__Fallback">Not Found</Avatar.Fallback>
    <Avatar.Image :src="props.src" :alt="props.alt" class="Avatar__Image" />
  </Avatar.Root>
</template>

// react/src/components/Avatar.tsx
import { Avatar as ArkAvatar } from "@ark-ui/react";

type Props = {
  src: string;
  alt: string;
};

export const Avatar = (props: Props) => (
  <ArkAvatar.Root className="Avatar">
    <ArkAvatar.Fallback className="Avatar__Fallback">
      Not Found
    </ArkAvatar.Fallback>
    <ArkAvatar.Image
      src={props.src}
      alt={props.alt}
      className="Avatar__Image"
    />
  </ArkAvatar.Root>
);
